### ISSUE TITLE
Expose mongoose object directly: 'RangeError: Maximum call stack size exceeded'

### ISSUE THREAD

**Issue by simonspoerri** [expressjs/express-expose#30]
I'm trying to directly expose a mongoose object within the callback of the mongoose's find method. When calling res.expose(mongooseObject, 'mongooseObjectName') this results in a the following error:

RangeError: Maximum call stack size exceeded

I don't know if this is an error caused by mongoose or by expose. Does anybody know what's happening here and how i could fix it?

**Comment by dx-sadaf** [comment]
@premjg @gregwym I have used this method but the issue is that my data have a field for date and it is not being escaped, thus resulting in javascript error. Any suggestion?
